services:
  gerador-nf:
    build: .
    ports:
      - "8080:8080"
    mem_limit: 512m
    cpus: "0.50"
    environment:
      TZ: America/Sao_Paulo
      JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -Duser.timezone=America/Sao_Paulo"